### ISSUE TITLE
Fails to install on my server

### ISSUE THREAD

**Issue by 360disrupt** [bauhausjs/phantom-html2pdf#20]
On my mac I get the plugin working but on the server npm throws this error. All other packages go through. I'm using an old version of nodejs (0.12) but I'm also using the same version on my mac.
```
> phantomjs@1.9.19 install /var/opt/im/nat/node_modules/phantom-html2pdf/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Kann exec nicht ausführen: Datei oder Verzeichnis nicht gefunden
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Kann exec nicht ausführen: Datei oder Verzeichnis nicht gefunden
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
npm ERR! Linux 3.10.0-229.20.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantom-html2pdf" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/opt/im/nat/npm-debug.log
```

npm log file
```
73671 verbose pkgid phantomjs@1.9.19
73672 verbose cwd /var/opt/im/lok
73673 error Linux 3.10.0-229.20.1.el7.x86_64
73674 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
73675 error node v0.12.7
73676 error npm  v2.11.3
73677 error code ELIFECYCLE
73678 error phantomjs@1.9.19 install: `node install.js`
73678 error Exit status 1
73679 error Failed at the phantomjs@1.9.19 install script 'node install.js'.
73679 error This is most likely a problem with the phantomjs package,
73679 error not with npm itself.
73679 error Tell the author that this fails on your system:
73679 error     node install.js
73679 error You can get their info via:
73679 error     npm owner ls phantomjs
73679 error There is likely additional logging output above.
73680 verbose exit [ 1, true ]
73681 verbose unbuild node_modules/phantom-html2pdf/node_modules/phantomjs
73682 info preuninstall phantomjs@1.9.19
73683 info uninstall phantomjs@1.9.19
73684 verbose unbuild rmStuff phantomjs@1.9.19 from /var/opt/im/lok/node_modules
73685 verbose unbuild rmStuff in /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules
73686 silly gentlyRm /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/.bin/phantomjs is being gently removed
73687 silly gentlyRm verifying /var/opt/im/lok is an npm working directory
73688 silly gentlyRm containing path /var/opt/im/lok is under npm's control, in /var/opt/im/lok
73689 silly gentlyRm deletion target /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/.bin/phantomjs is under /var/opt/im/lok
73690 verbose gentlyRm vacuuming from /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/.bin/phantomjs up to /var/opt/im/lok
73691 silly vacuum-fs removing /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/.bin/phantomjs
73692 silly vacuum-fs removing /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/.bin
73693 silly vacuum-fs quitting because other entries in /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules
73694 info postuninstall phantomjs@1.9.19
73695 silly gentlyRm /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/phantomjs is being purged from base /var/opt/im/lok
73696 verbose gentlyRm don't care about contents; nuking /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/phantomjs
73697 silly vacuum-fs purging /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules/phantomjs
73698 silly vacuum-fs quitting because other entries in /var/opt/im/lok/node_modules/phantom-html2pdf/node_modules
73699 verbose unbuild node_modules/phantom-html2pdf
73700 info preuninstall phantom-html2pdf@1.0.2
73701 info uninstall phantom-html2pdf@1.0.2
73702 verbose unbuild rmStuff phantom-html2pdf@1.0.2 from /var/opt/im/lok/node_modules
73703 silly gentlyRm /var/opt/im/lok/node_modules/.bin/phantom-html2pdf is being gently removed
73704 silly gentlyRm verifying /var/opt/im/lok is an npm working directory
73705 silly gentlyRm containing path /var/opt/im/lok is under npm's control, in /var/opt/im/lok
73706 silly gentlyRm deletion target /var/opt/im/lok/node_modules/.bin/phantom-html2pdf is under /var/opt/im/lok
73707 verbose gentlyRm vacuuming from /var/opt/im/lok/node_modules/.bin/phantom-html2pdf up to /var/opt/im/lok
73708 info postuninstall phantom-html2pdf@1.0.2
73709 silly gentlyRm /var/opt/im/lok/node_modules/phantom-html2pdf is being purged from base /var/opt/im/lok
73710 verbose gentlyRm don't care about contents; nuking /var/opt/im/lok/node_modules/phantom-html2pdf
73711 silly vacuum-fs purging /var/opt/im/lok/node_modules/phantom-html2pdf
73712 silly vacuum-fs quitting because other entries in /var/opt/im/lok/node_modules
73713 verbose unbuild node_modules/karma-phantomjs-launcher/node_modules/phantomjs
73714 info preuninstall phantomjs@1.9.19
73715 info uninstall phantomjs@1.9.19
```

**Comment by dustin-H** [comment]
hmm, looks like a problem of phantomjs, not like one of this module. May you are trying to install two different versions of phantomjs?

**Comment by 360disrupt** [comment]
With the newer node version it seems to work. Maybe I updated phantomjs on the way.
