### ISSUE TITLE
spawn /phantom/bin/phantomjs

### ISSUE THREAD

**Issue by VoxFoxMC** [bauhausjs/phantom-html2pdf#58]
I found similar question but none of them seemed to have answers that worked so I thought I'd post here.
```
Debug: internal, implementation, error 
    Error:  method did not return a value, a promise, or throw an error
    at e.exports.s.Manager.execute (/home/voxfox/workspace/web/bw_admin/server/dist/js/api-bundle.js:13:499438)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pdf.convert: Error: spawn /phantom/bin/phantomjs ENOENT
```
If that error is saying what I think it is, it's not appending the path to phantom-html2pdf to the beginning of the string. Any ideas what I need to do to fix this?

**Comment by VoxFoxMC** [comment]
Looks like I needed to install phantomjs-prebuilt globally, but to do that I needed to install nvm because I was getting permission problems without it.
